version: "3"

vars: {}
dotenv: [".env"]

tasks:
  # 初期環境構築用タスク
  init:
    desc: Initialize project.
    deps:
      - clean
    cmds:
      - git submodule update --init --recursive
      - npm install -D
  clean:
    # rmは環境によって利用できないのでgit cleanを利用する。
    desc: Clean files.
    cmds:
      - git clean -fdx themes/PaperMod
      - git clean -fdx node_modules

  build:
    desc: Build site.
    cmds:
      - hugo --gc --minify --config=config.yml
  serve:
    desc: Serve site.
    cmds:
      - hugo server -DFE --config=config.yml {{.CLI_ARGS}}

  # linter, formatter
  lint:
    desc: Lint files.
    cmds:
      - dprint check
      - npx prettier --check "**/*.{yml,yaml}"
      - npx cspell lint .
  format:
    desc: Format files.
    cmds:
      - dprint fmt
      - npx prettier --write "**/*.{yml,yaml}"
